### ISSUE TITLE
Azure Sql Server Composite error: 'Cannnot register providers: Microsoft.DataProtection'

### ISSUE THREAD

**Issue by fsniper** [crossplane-contrib/provider-jet-azure#104]
### What happened?
While working on azure jet sql server hit a strange error.
```
      observe failed: cannot run refresh: refresh failed: Error ensuring Resource Providers are registered.

      Terraform automatically attempts to register the Resource Providers it supports to
      ensure it's able to provision resources.

      If you don't have permission to register Resource Providers you may wish to use the
      "skip_provider_registration" flag in the Provider block to disable this functionality.

      Please note that if you opt out of Resource Provider Registration and Terraform tries
      to provision a resource from a Resource Provider which is unregistered, then the errors
      may appear misleading - for example:

      > API version 2019-XX-XX was not found for Microsoft.Foo

      Could indicate either that the Resource Provider "Microsoft.Foo" requires registration,
      but this could also indicate that this Azure Region doesn't support this API version.

      More information on the "skip_provider_registration" flag can be found here:
      https://www.terraform.io/docs/providers/azurerm/index.html#skip_provider_registration

      Original Error: Cannnot register providers: Microsoft.DataProtection. Errors were: Cannot register provider Microsoft.DataProtection with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '49e1a86b-9122-4cc2-af2d-b44a3a6a791e' with object id '49e1a86b-9122-4cc2-af2d-b44a3a6a791e' does not have authorization to perform action 'Microsoft.DataProtection/register/action' over scope '/subscriptions/c168b5be-f709-4323-96db-30b47c700ef6' or the scope is invalid. If access was recently granted, please refresh your credentials.".: : File name: main.tf.json
```

While using the crossplane resources directly I didn't get this error. I only hit this error while using composites.
Do you know what is this related to? 

### How can we reproduce it?
Here is my composite and related claim:
```
# Source: msai-crossplane-xrds/templates/azuresql-composition.yaml
# Sample used is: https://github.com/crossplane/crossplane/discussions/2192
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azuresqlserver
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: ptc.io/v1alpha1
    kind: AzureSqlServerComposite
  patchSets:
  - name: Metadata
    patches:
    - fromFieldPath: metadata.labels
    - fromFieldPath: metadata.annotations
  resources:
  # db-server
  - base:
      apiVersion: sql.azure.jet.crossplane.io/v1alpha1
      kind: Server
      spec:
        forProvider:
          version: "12.0"
          resourceGroupName: "clusterRG-crossplane"
          administratorLogin: "adminuser"
          administratorLoginPasswordSecretRef:
            name: "secret-name"
            key: "password"
            namespace: "namespace"
        writeConnectionSecretToRef:
          namespace: crossplane-system
    patches:
    - type: PatchSet
      patchSetName: Metadata
    - fromFieldPath: "metadata.name"
      toFieldPath: "spec.forProvider.serverName"
    - fromFieldPath: "spec.parameters.location"
      toFieldPath: "spec.forProvider.location"
    - fromFieldPath: "spec.parameters.administrator_login_name"
      toFieldPath: "spec.forProvider.administratorLogin"
    - fromFieldPath: "spec.parameters.administrator_login_secret_name"
      toFieldPath: "spec.forProvider.administratorLoginPasswordSecretRef.name"
    - fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
      toFieldPath: "spec.forProvider.administratorLoginPasswordSecretRef.namespace"
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: "metadata.name"
        - fromFieldPath: "metadata.uid"
        strategy: string
        string:
          fmt: "%s-%s"
      toFieldPath: spec.writeConnectionSecretToRef.name
      policy:
        fromFieldPath: Required
    connectionDetails:
    - fromConnectionSecretKey: username
    - fromConnectionSecretKey: password
    - fromConnectionSecretKey: endpoint
    - fromConnectionSecretKey: port
```
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: azuresqlservercomposites.ptc.io
  labels:
    helm.sh/chart: msai-crossplane-xrds-0.2.2
    app.kubernetes.io/name: msai-crossplane-xrds
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  group: ptc.io
  names:
    kind: AzureSqlServerComposite
    plural: azuresqlservercomposites
  claimNames:
    kind: AzureSqlServer
    plural: azuresqlservers
  defaultCompositionRef:
    name: azuresqlservercomposite
  connectionSecretKeys:
  - endpoint
  - port
  - password
  - username
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  location:
                    description: Geographic location of this PostgreSQL server.
                    type: string
                    default: eastus
                  administrator_login_name:
                    description: Admin User Name for this Azure SQL server.
                    type: string
                    default: "adminuser"
                  administrator_login_secret_name:
                    description: Name of the secret holding password for the administrator login user
                    type: string
                    default: "adminpassword"
                required:
                - location
                - administrator_login_name
                - administrator_login_secret_name
            required:
            - parameters
```

### What environment did it happen in?
Crossplane version: uxp-1.4.0-up.1
azure-jet: v0.4.0
k8s version: v1.20.7
