### ISSUE TITLE
Cannot refresh private kubernetes cluster - Conflicting configuration arguments

### ISSUE THREAD

**Issue by fherbert** [crossplane-contrib/provider-jet-azure#106]
### What happened?
A kubernetes cluster resource was created successfully, but it seems there are some fields (private_link_enabled) that update the managed resource after it is created.
```
    Message:               observe failed: cannot run refresh: refresh failed: Conflicting configuration arguments: "private_link_enabled": conflicts with private_cluster_enabled: File name: main.tf.json
Conflicting configuration arguments: "private_cluster_enabled": conflicts with private_link_enabled: File name: main.tf.json
```

When we apply the clusterclaim the initially created kubernetescluster resource does not have the privateLinkEnabled parameters in the forProvider object. Once it's created however, I'm guessing it does some sort of refresh/update from azure and adds a new parameter in the forProvider object "privateLinkEnabled: true". This results in the above message as both private_link_enabled and private_cluster_enabled cannot both be set.

### How can we reproduce it?
The following composition was created
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster-azure
  labels:
    provider: azure
    cluster: aks
spec:
  compositeTypeRef:
    apiVersion: rfod.com/v1alpha1
    kind: CompositeCluster
  writeConnectionSecretsToNamespace: crossplane
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: aks
    base:
      apiVersion: containerservice.azure.jet.crossplane.io/v1alpha1
      kind: KubernetesCluster
      spec:
        forProvider:
          addonProfile:
          - azurePolicy:
            - enabled: false
          defaultNodePool:
          - maxCount: 10
            enableAutoScaling: true
            vmSize: Standard_D8s_v3
            vnetSubnetId: /subscriptions/1111111-11111-1111-1111-1111111111/resourceGroups/Someotherresourcegroup/providers/Microsoft.Network/virtualNetworks/somevnet/subnets/subnetname
            availabilityZones:
            - "1"
            - "2"
            - "3"
          dnsPrefixPrivateCluster: rfod
          identity:
          - type: UserAssigned
            userAssignedIdentityId: /subscriptions/1111111-11111-1111-1111-1111111111/resourceGroups/someresourcegroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umi
          kubernetesVersion: "1.21.2"
          location: australiaeast
          networkProfile:
          - networkPlugin: kubenet
            networkPolicy: calico
            outboundType: userDefinedRouting
          privateClusterEnabled: true
          privateDnsZoneId: /subscriptions/1111111-11111-1111-1111-1111111111/resourceGroups/someresourcegroup/providers/Microsoft.Network/privateDnsZones/privatelink.australiaeast.azmk8s.io
          resourceGroupName: ResourceGroupName
          roleBasedAccessControl:
          - enabled: true
            azureActiveDirectory:
            - managed: true
              adminGroupObjectIds:
              - 11111111-1111-1111-1111-1111111111111
          skuTier: Paid
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.name
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
        - type: string
          string:
            fmt: "%s-akscluster"
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.defaultNodePool[0].name
    - fromFieldPath: spec.parameters.version
      toFieldPath: spec.forProvider.kubernetesVersion
    - fromFieldPath: spec.parameters.minNodeCount
      toFieldPath: spec.forProvider.defaultNodePool[0].minCount
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.forProvider.defaultNodePool[0].vmSize
      transforms:
      - type: map
        map:
          small: Standard_D2_v2
          medium: Standard_D8s_v3
          large: Standard_D16_v3
    - type: ToCompositeFieldPath
      fromFieldPath: spec.id
      toFieldPath: status.clusterName
    - type: ToCompositeFieldPath
      fromFieldPath: status.conditions[0].status
      toFieldPath: status.controlPlaneStatus
    - type: ToCompositeFieldPath
      fromFieldPath: status.conditions[0].status
      toFieldPath: status.nodePoolStatus
    - fromFieldPath: spec.writeConnectionSecretToRef.namespace
      toFieldPath: spec.writeConnectionSecretToRef.namespace
    readinessChecks:
    - type: MatchString
      fieldPath: status.conditions.status
      matchString: Succeeded
    connectionDetails:
      - fromConnectionSecretKey: kubeconfig
```

### What environment did it happen in?
Crossplane 1.5.0
provider-jet-azure - v0.3.0
AKS - 121.2
