### ISSUE TITLE
Failing `azurerm_key_vault_managed_storage_account` Example

### ISSUE THREAD

**Issue by ulucinar** [crossplane-contrib/provider-jet-azure#128]
### What happened?

Although the generated managed resource for `azurerm_key_vault_managed_storage_account` is configured in #119, the following example manifest fails with the following error:
```
  - message: 'apply failed: creating Managed Storage Account example-vaultstorageaccount:
      keyvault.BaseClient#SetStorageAccount: Failure responding to request: StatusCode=404
      -- Original Error: autorest/azure: error response cannot be parsed: "<!DOCTYPE
      html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html
      xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\"
      content=\"text/html; charset=iso-8859-1\"/>\r\n<title>404 - File or directory
      not found.</title>\r\n<style type=\"text/css\">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana,
      Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px
      10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-si" error:
      invalid character ''<'' looking for beginning of value: : File name: main.tf.json'
    reason: ApplyFailure
    status: "False"
    type: AsyncOperation
```

This looks like an issue with the example manifests/misconfiguration of the Cloud resources themselves, but we need to investigate and provide a working manifest and bump `ManagedStorageAccount`'s version to `v1alpha2`.

### How can we reproduce it?

The following manifest was used together with the `Vault` example manifest already provided in the repo:
```yaml
apiVersion: keyvault.azure.jet.crossplane.io/v1alpha2
kind: Vault
metadata:
  name: examplekeyvault-alper2
spec:
  forProvider:
    enabledForDiskEncryption: true
    location: West Europe
    purgeProtectionEnabled: false
    resourceGroupNameRef:
      name: example
    skuName: standard
    softDeleteRetentionDays: 7
    tenantId: <tenant id>
  providerConfigRef:
    name: example

---

# This example manifest is auto-generated, and has not been tested.
# Please make the necessary adjustments before using it.
apiVersion: keyvault.azure.jet.crossplane.io/v1alpha1
kind: ManagedStorageAccount
metadata:
  name: example-vaultstorageaccount
spec:
  forProvider:
    keyVaultIdRef:
      name: examplekeyvault-alper2
    storageAccountIdRef:
      name: example-storage-account

    storageAccountKey: key1
    regenerateKeyAutomatically: true
    regenerationPeriod: P1D

  providerConfigRef:
    name: example
```
