### ISSUE TITLE
Unable to create cosmos account

### ISSUE THREAD

**Issue by sivarajp** [crossplane-contrib/provider-jet-azure#157]
### What happened?
Tried to create cosmos account 

```

apiVersion: cosmosdb.azure.jet.crossplane.io/v1alpha2
kind: Account
metadata:
  name: demo-cosmosdb-mongo
spec:
  forProvider:
    kind: MongoDB
    location:  "East Us 2"
    offerType: Standard
    mongoServerVersion: "4.0"
    backup:
    - type: Continuous
    consistencyPolicy:
    - consistencyLevel: Session
    resourceGroupNameRef:
      name: demo-rg
    geoLocation:
    - failoverPriority: 0
      location: "East Us 2"
      zoneRedundant: True

    capabilities:
    - name: EnableMongo
    - name: DisableRateLimitingResponses

  providerConfigRef:
    name: example
  writeConnectionSecretToRef:
    name: conn-example-cosmos
    namespace: demo    
```

Received error: 
managed/cosmosdb.azure.jet.crossplane.io/v1alpha2, kind=account cannot get a terraform workspace for resource: cannot reproduce tfstate file: cannot get id: “attribute not found: account_name.

### How can we reproduce it?
Try creating azure cosmos DB account

### What environment did it happen in?
Crossplane version: v1.6.2

Terrajet version: 0.7.0 (0.8.0 also has the same)

Looks like the issue is in this block azurerm_cosmosdb_account
r.ExternalName.GetIDFn = common.GetFullyQualifiedIDFn(“Microsoft.DocumentDB”, “databaseAccounts”, “account_name”)

The account name is not supplied as cred as we havent create the cosmos account yet.  We need to pass name as args. 

I can submit a PR if needed
