### ISSUE TITLE
Kind NetworkInterface doesn't work

### ISSUE THREAD

**Issue by alisson276** [crossplane-contrib/provider-jet-azure#159]
### What happened?

Applying a NetworkInterface resource fails.

As far I as could debug the process (entering in the container and running terraform plan by hand), the problem is in the parameters passed to terraform.

The error from the plan is:
```
Error: Key/Value cannot be empty strings. Key: 'providers', Value: ''
```

The problem is, if I get the same main.tf.json and apply in another folder everything works
```
cd /tmp
cp -a 73d8254b-0415-499e-b5a0-a7883894d7f0 x
cd x
rm terraform.tfstate
terraform plan -out plan
terraform apply plan
```

### How can we reproduce it?

resources.yaml
```
apiVersion: azure.jet.crossplane.io/v1alpha2
kind: ResourceGroup
metadata:
  name: example
spec:
  forProvider:
    location: West Europe
  providerConfigRef:
    name: default
---
apiVersion: network.azure.jet.crossplane.io/v1alpha2
kind: VirtualNetwork
metadata:
  name: vnet-example
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    location: West Europe
    subnet: []
    dnsServers: []
    resourceGroupNameRef:
      name: example
    tags:
      environment: Production
  providerConfigRef:
    name: default
---
apiVersion: network.azure.jet.crossplane.io/v1alpha2
kind: Subnet
metadata:
  name: subnet-example
spec:
  forProvider:
    addressPrefixes:
    - 10.0.1.0/24
    resourceGroupNameRef:
      name: example
    virtualNetworkNameRef:
      name: vnet-example
  providerConfigRef:
    name: default
---
apiVersion: network.azure.jet.crossplane.io/v1alpha2
kind: NetworkInterface
metadata:
  name: nic-example
spec:
  forProvider:
    ipConfiguration:
    - name: internal
      primary: true
      privateIpAddressAllocation: Dynamic
      subnetIdRef:
        name: subnet-example
    location: West Europe
    resourceGroupNameRef:
      name: example
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version: 1.6.5
provider-jet-azure: 0.8.0-preview
