### ISSUE TITLE
Subnet spec.forProvider.addressPrefix causes observe errors

### ISSUE THREAD

**Issue by natereid72** [crossplane-contrib/provider-jet-azure#178]
### What happened?

Create Subnet with spec.forProvider.addressPrefix configured. Subnet creates ok in Azure cloud. MR reports Ready:True/Synced:False.

Config used:

```yaml
    - base:
        apiVersion: network.azure.jet.crossplane.io/v1alpha2
        kind: Subnet
        spec:
          forProvider:
            resourceGroupNameSelector:
              matchControllerRef: true
            virtualNetworkNameSelector:
              matchControllerRef: true
            addressPrefix: "192.168.1.0/24"
            serviceEndpoints: ["Microsoft.Sql"]
```

Error reported with `kubectl describe` on MR:

```
Warning  CannotObserveExternalResource  5m22s (x7 over 10m)  managed/network.azure.jet.crossplane.io/v1alpha2, kind=subnet  cannot run refresh: refresh failed: Invalid combination of arguments: "address_prefixes": only one of `address_prefix,address_prefixes` can be specified, but `address_prefix,address_prefixes` were specified.: File name: main.tf.json
```

When trying to delete the XR/MR, it hangs for a long time and then produces this error:

```
error: An error occurred while waiting for the object to be deleted: an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 167; INTERNAL_ERROR; received from peer") has prevented the request from succeeding
```

### How can we reproduce it?

Create this resource as above? 

### What environment did it happen in?

* Crossplane version:  1.5.1 (UbC hosted)
* crossplane/provider-jet-azure:v0.9.0
