### ISSUE TITLE
ServiceBus does not appear to exist though generated examples show it

### ISSUE THREAD

**Issue by jtreuting** [crossplane-contrib/provider-jet-azure#191]
### What happened?

When using the generated examples for a servicebus provided here: https://github.com/crossplane-contrib/provider-jet-azure/blob/release-0.10/examples-generated/servicebus/queue.yaml, the response after doing a simple apply is `no matches for kind "Queue" in version "servicebus.azure.jet.crossplane.io/v1alpha1"`. 

When I look at the documentation provided (https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-azure@v0.10.0) I don't see any ServiceBus listed.

### How can we reproduce it?

I used the generated example from the documentation and altered the resource group like so:

```
apiVersion: servicebus.azure.jet.crossplane.io/v1alpha1
kind: Queue
metadata:
  name: my-queue
spec:
  forProvider:
    enablePartitioning: true
    name: my-queue
    namespaceName: my-queue-namespace
    resourceGroupNameRef:
      name: my-resource-group
```

I also searched the installed CRDs for the provider and don't see servicebus listed anywhere.  I only see the IoT servicebus listed:

```
kubectl get crd | grep servicebus
iothubendpointservicebusqueues.devices.azure.jet.crossplane.io              2022-06-10T07:32:17Z
iothubendpointservicebustopics.devices.azure.jet.crossplane.io              2022-06-10T07:32:20Z
```

### What environment did it happen in?
Crossplane version: v0.9 and v0.10
