### ISSUE TITLE
Cannot create container registry

### ISSUE THREAD

**Issue by davemaul** [crossplane-contrib/provider-jet-azure#199]
### What happened?
I tried to create a container registry with this provider. The process failed with the following error message:

```
observe failed: cannot run refresh: refresh failed: Missing required
argument: The argument "encryption.0.identity_client_id" is required,
but no definition was found.: File name: main.tf.json

Missing required argument: The argument "encryption.0.key_vault_key_id"
is required, but no definition was found.: File name: main.tf.json
```

This is weird because I don't want to use encryption at all. The field is optional as documented [here](https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-azure/containerregistry.azure.jet.crossplane.io/Registry/v1alpha1@v0.12.0-preview). I tried to fix it by setting `encryption.enabled: false` but this didn't work out either.

### How can we reproduce it?
```
apiVersion: containerregistry.azure.jet.crossplane.io/v1alpha1
kind: Registry
metadata:
  name: registry
  namespace: {{ .Release.Namespace }}
spec:
  forProvider:
    name: {{ .Values.registryName }}
    resourceGroupName: {{ .Values.rg }}
    location: {{ .Values.location }}
    adminEnabled: true
    sku: Basic
  providerConfigRef:
    name: provider-jet-azure
```

This is a fairly simple setup.

### What environment did it happen in?
Crossplane version: v1.9.0
Provider Version: v0.12.0-preview
Kubernetes: AKS 1.23.8

Thanks in advance!
