### ISSUE TITLE
Provider produced inconsistent result after apply account.storage.azure.jet.crossplane.io

### ISSUE THREAD

**Issue by jribmartins** [crossplane-contrib/provider-jet-azure#212]
### What happened?

I just want to create an azure storage account but the resource wasn't created, the message:
```
Message:  apply failed: Provider produced inconsistent result after apply: When applying changes to azurerm_storage_account.cbs-storage-sandbox-premium, provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was present, but now absent.
This is a bug in the provider, which should be reported in the provider's own issue tracker.
Reason:  ApplyFailure
```

### How can we reproduce it?

Just apply the following storageaccount:
```yaml
apiVersion: storage.azure.jet.crossplane.io/v1alpha2
kind: Account
metadata:
  name: cbs-storage-sandbox-premium
  labels:
    name: cbs-storage-sandbox-premium
  annotations:
    crossplane.io/external-name: cbssfs
spec:
  forProvider:
    location: westeurope
    resourceGroupName: cbs-k8s-nodes
    accountKind: FileStorage
    accountTier: Premium
    accountReplicationType: LRS
    enableHttpsTrafficOnly: true
    minTlsVersion: TLS1_2
    allowBlobPublicAccess: false
    identity:
      - type: "SystemAssigned"
    networkRules:
      - defaultAction: Deny
        virtualNetworkSubnetIds:
          - "mysubnetId"
```

### What environment did it happen in?
Crossplane:  v1.10.1
Kubernetes v1.22.6
provider-jet-azure-controller v0.12.0-preview

Thank you
