### ISSUE TITLE
postgresql_configuration sync issue

### ISSUE THREAD

**Issue by ulucinar** [crossplane-contrib/provider-jet-azure#97]
### What happened?

Using the example manifests in the repo for postgresql server and postgresql server configuration, postgresql server object is successfully provisioned, becomes ready & synced and is stable, i.e., it stays in ready & synced state.

However, although initially postgresql configuration object becomes ready & synched, after a while it transitions to the ready but not-synced state because if the following error in `ExternalClient.Observe`:
```yaml
    message: 'observe failed: cannot run plan: plan failed: Instance cannot be destroyed:
      Resource azurerm_postgresql_configuration.example-psql-configuration has lifecycle.prevent_destroy
      set, but the plan calls for this resource to be destroyed. To avoid this error
      and continue with the plan, either disable lifecycle.prevent_destroy or reduce
      the scope of the plan using the -target flag.: File name: main.tf.json'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### How can we reproduce it?

This can be reproduced using the example manifests mentioned above.

**Comment by muvaf** [comment]
> Instance cannot be destroyed

It seems like Terraform execution tried to delete this resource, which is probably because it detected a change in a field that is immutable. I think what we need to figure out is why suddenly it thought that a diff on that field exists without a user action.

**Comment by ulucinar** [comment]
Looks like this is related to the intricacies involved with these server configuration resources. For example, for the initial attempt (i.e., no configuration resource has initially been provisioned), the following manifest is successfully applied with `terraform apply`:
```
{
  "provider": {
    "azurerm": {
      "features": {}
    }
  },
  "resource": {
    "azurerm_postgresql_configuration": {
      "example-psql-configuration": {
        "lifecycle": {
          "prevent_destroy": true
        },
        "name": "array_nulls",
        "resource_group_name": "alper",
        "server_name": "example-psqlserver-alper",
        "value": "on"
      }
    }
  },
  "terraform": {
    "required_providers": {
      "azurerm": {
        "source": "hashicorp/azurerm",
        "version": "2.78.0"
      }
    }
  }
}
```

Note the `prevent_destroy` meta-arg. After this initial run, if you just change the configuration's value to `off` and rerun the same `terraform apply` command, it fails because of the lifecycle meta arg.

I did not check but it looks like it's implemented via a destroy. Btw, the Go SDK does not have a delete call but a createOrUpdate call AFAIR.

**Comment by muvaf** [comment]
It seems like there are two cases here:
* User changes `value` and terraform tries to re-create it.
  * Because that field is marked as `ForceNew`, i.e. immutable in Crossplane world: https://github.com/hashicorp/terraform-provider-azurerm/blob/3eefe84/internal/services/postgres/postgresql_configuration_resource.go#L54
* User does nothing and suddenly starts to see that error.
  * This could be related to late-init or plan functionality that causes `IsUpToDate` to return false negatives, which is worth looking into.

@ulucinar Is it the second one or the first one that you're seeking to solve by making `lifecycle.prevent_destroy` optional?

**Comment by ulucinar** [comment]
To clarify the above discussion, it's related to updates. For instance, if you are provisioning a configuration resource whose value (`spec.forProvider.value`) is different than the default value (or whatever the value currently set at server side).

**Comment by ulucinar** [comment]
What we are dealing with here is related to the first one. The spec parameters do not change (due to late-init):

```yaml
spec:
  deletionPolicy: Delete
  forProvider:
    resourceGroupName: alper
    resourceGroupNameRef:
      name: example
    serverName: example-psqlserver-alper
    serverNameRef:
      name: example-psqlserver-alper
    value: "off"
  providerConfigRef:
    name: example
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2021-11-24T19:01:54Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-11-24T19:01:54Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```

and then we get:

```yaml
spec:
  deletionPolicy: Delete
  forProvider:
    resourceGroupName: alper
    resourceGroupNameRef:
      name: example
    serverName: example-psqlserver-alper
    serverNameRef:
      name: example-psqlserver-alper
    value: "off"
  providerConfigRef:
    name: example
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2021-11-24T19:01:54Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-11-24T19:02:13Z"
    message: 'observe failed: cannot run plan: plan failed: Instance cannot be destroyed:
      Resource azurerm_postgresql_configuration.example-psql-configuration has lifecycle.prevent_destroy
      set, but the plan calls for this resource to be destroyed. To avoid this error
      and continue with the plan, either disable lifecycle.prevent_destroy or reduce
      the scope of the plan using the -target flag.: File name: main.tf.json'
    reason: ReconcileError
    status: "False"
    type: Synced
```

In the above example, the server-side configuration holds an `on`, and we have `off` in the `spec`, thus an update is needed. 

What confuses me, is why we declare it as `Ready` in the first hand. But regardless of this, the `prevent_destroy` seems to be blocking proper updates for this resource.
